//! Rust wrappers for the types in the "linux/sev-step/sev-step.h" header.
//! Autogenerated in build.rs
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
